apiVersion: v1
kind: Pod
metadata:
  name: fortune
  labels:
    app: kubia
spec:
  containers:
    # 첫 번재 컨테이너는 html-generator 라고 이름 짓고 luksa/fortune 이미지를 실행한다
    - image: luksa/fortune
      name: html-generator
      # html 이름의 볼륨을 컨테이너의 /var/htdocs 에 마운트한다
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
    # 두 번째 컨테이너는 web-server 라고 이름 짓고 nginx:alpine 이미지를 실행한다
    - image: nginx:alpine
      name: web-server
      # 위와 동일한 볼륨을 /usr/share/nginx/html 에 읽기 전용으로 마운트한다
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
    # html 이란 단일 emptyDir 볼륨을 위의 컨테이너 두 개에 마운트한다
  volumes:
    - name: html
      emptyDir: {}
      # emptyDir 은 워커 노드의 디스크에 생성되므로, 노드 디스크의 성능의 영향을 받는다
      # 다음과 같이 tmpfs 파일 시스템으로 메모리를 파일시스템으로 생성하도록 정의할 수 있다
      # emptyDir:
      #   medium: Memory
