apiVersion: v1
kind: Pod
metadata:
  name: fortune-https
spec:
  containers:
    - image: luksa/fortune:env
      name: html-generator
      env:
        - name: INTERVAL
          valueFrom:
            configMapKeyRef:
              name: fortune-config
              key: sleep-interval
        # 시크릿의 개별 항목을 환경 변수로 노출할 수도 있다
        # 그러나 시크릿을 환경 변수로 노출하는건 best practice 가 아니다. 앱이 오류 보고서에 환경 변수를 기록하거나 로그에 환경변수가 남아 의도치 않게 노출될 수 있기 때문이다
        # 즉 best practice 는 secret 볼륨을 사용하는 것이다
        - name: FOO_SECRET
          valueFrom:
            secretKeyRef:
              name: fortune-https
              key: foo
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
    - image: nginx:alpine
      name: web-server
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        # Nginx 서버가 인증서와 키를 /etc/nginx/certs 에서 읽도록 설정했기 때문에 시크릿 볼륨을 해당 위치에 마운트한다
        - name: certs
          mountPath: /etc/nginx/certs/
          readOnly: true
      ports:
        - containerPort: 80
        - containerPort: 443
  volumes:
    - name: html
      emptyDir: {}
    - name: config
      configMap:
        name: fortune-config
        items:
          - key: my-nginx-config.conf
            path: https.conf
    # fortune-https 시크릿을 참조하도록 시크릿 볼륨을 정의한다
    - name: certs
      secret:
        secretName: fortune-https
