apiVersion: v1
kind: Pod
metadata:
  name: fortune-configmap-volume
spec:
  containers:
    - image: luksa/fortune:env
      name: html-generator
      env:
        - name: INTERVAL
          valueFrom:
            configMapKeyRef:
              name: fortune-config
              key: sleep-interval
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
    - image: nginx:alpine
      name: web-server
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        # 컨피그맵을 참조하는 볼륨을 마운트한다
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
  volumes:
    - name: html
      emptyDir: {}
    # 이 볼륨은 fortune-config 컨피그맵을 참조한다
    - name: config
      # item 속성 없이 정의하면 config 볼륨이 참조하는 fortune-config 컨피그맵의 모든 설정파일이 이 볼륨을 사용하는 컨테이너 파일시스템에 마운트된다
      # 즉, web-server 의 /etc/nginx/conf.d 에는 my-nginx-config.con 와 sleep-interval 이 포함된다
      configMap:
        name: fortune-config
        # 지정된 컨피그맵 항목만 파일 디렉터리에 마운트하려면 다음과 같이 item 을 정의할 수 있다
        # 이러면 볼륨에 포함할 항목을 조회해서 선택할 수 있다
        items:
          # 주어진 키의 value 를 포함한다
          - key: my-nginx-config.conf
            # 항목 값이 지정된 파일에 저장된다. 즉 web-server 의 /etc/nginx/conf.d 디렉터리에는 gzip.conf 파일만 포함한다
            path: gzip.conf
