apiVersion: v1
kind: Pod
metadata:
  name: fortune2s-args-configmap
  labels:
    app: kubia
spec:
  containers:
    # 환경변수가 아닌 args 로 부턴 interval 를 가져오는 이미지 사용
    - image: luksa/fortune:args
      name: html-generator
      # 컨피그맵에서 환경변수 정의
      env:
        - name: INTERVAL
          valueFrom:
            configMapKeyRef:
              name: fortune-config
              key: sleep-interval
      # 환경변수로 지정한 값을 argument 로 사용
      args: ["$(INTERVAL)"]
# 아래는 chapter06/fortune-pod.yaml 과 동일하다
